print("Hello from conflict branch")
print("My first git Project")
print("Git practice day one")
print("Learning GitHub")
print("Learning git pull")
print("practicing git fetch")
print("This is my practice branch")
